# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0  

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run npm install
          command: npm i
      - save_cache:
          key: "npm-packages"
          paths:
            - /src/node_modules
      - run:
          name: Run npm lint   
          command: npm lint

      - run:
          name: If this job fails, rollback
          command: echo The App is on fire
          when: on_fail  

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run:
          name: Run npm install
          command: npm i
      - run:
          name: Run Tests
          command: npm run test

  analize:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: "npm-packages" 
      - run:
          name: Run npm audit.
          command: npm audit
      - run:
          name: This gonna fail... shit
          command: echo Another App on fire
          when: on_fail    
                
# Orchestrate or schedule a set of jobs
workflows:
  default:
    jobs:
      - build
      - test:
          requires: [build]
      - analize:
          requires: [test]

